// AUTO-GENERATED by @tsqlx/codegen
// Do not edit — regenerated on every build
// Source: report.tsq  |  Target: pg

import type { Pool, PoolClient } from "pg";

export interface GetPestReportInput {
  companyId: string;
  speciesId?: string;
  from: Date;
  to: Date;
}

export interface GetPestReportRow {
  species_name: string;
  total: number;
  avg_severity: number;
  location: string;
}

export async function getPestReport(
  db: Pool | PoolClient,
  input: GetPestReportInput,
): Promise<GetPestReportRow[]> {
  const _params: unknown[] = [input.companyId, input.from, input.to];
  let _sql = `
SELECT
s.name AS species_name,
COUNT (*)::int AS total,
AVG (s.severity)::float8 AS avg_severity,
ps.location AS location
FROM pest_sightings ps
JOIN species s ON s.id = ps.species_id
WHERE ps.company_id = $1
AND ps.created_at BETWEEN $2 AND $3
GROUP BY s.name, ps.location
ORDER BY total DESC`;

  if (input.speciesId != null) {
    _params.push(input.speciesId);
    _sql += `
AND ps.species_id = $4::uuid`.replace(
      /\$\d+/g,
      () => "$" + String(_params.length),
    );
  }

  const { rows } = await db.query<GetPestReportRow>({
    text: _sql,
    values: _params,
  });
  return rows;
}
