import type { Driver } from "@tsqlx/core";

// ─── Supported emit targets ───────────────────────────────────────────────────

export type EmitTarget =
  | "raw" // plain parameterised SQL string + typed input/output only
  | "pg" // node-postgres (pg) — also use this for Supabase Postgres (DATABASE_URL / pooler)
  | "drizzle" // same runtime as pg; use the Pool you pass to drizzle-orm/node-postgres
  | "prisma"; // prisma $queryRawUnsafe

// ─── Options ─────────────────────────────────────────────────────────────────

export interface CodegenOptions {
  /**
   * Output target. Determines which client import and call pattern is emitted.
   * Defaults to "raw" when no @driver directive is found.
   */
  target?: EmitTarget;

  /**
   * Prepend this banner comment to every generated file.
   * Set to false to suppress the banner.
   */
  banner?: string | false;

  /**
   * When true, emit `export const QUERY_NAME_SQL = "..."` string constants
   * alongside the typed functions. Useful for logging / query plan analysis.
   * Default: false
   */
  exportSqlStrings?: boolean;

  /**
   * Indentation string. Default: two spaces.
   */
  indent?: string;
}

// ─── Resolve driver → target ─────────────────────────────────────────────────

export function resolveTarget(
  driver: Driver | undefined,
  override: EmitTarget | undefined,
): EmitTarget {
  if (override) return override;
  if (!driver) return "raw";
  const map: Record<Driver, EmitTarget> = {
    postgres: "pg",
    mysql: "raw",
    sqlite: "raw",
    // Supabase = Postgres; @supabase/supabase-js has no safe arbitrary SQL API — use pg + pooler URL.
    supabase: "pg",
  };
  return map[driver];
}

// ─── Default banner ──────────────────────────────────────────────────────────

export const DEFAULT_BANNER = `// AUTO-GENERATED by @tsqlx/codegen
// Do not edit — regenerated on every build
// Source: {filename}  |  Target: {target}`;
